language: objective-c
osx_image: xcode8.3
xcode_workspace: flyve-mdm-ios.xcworkspace
xcode_scheme: flyve-mdm-ios
podfile: Podfile
before_install:
- chmod a+x scripts/add-key.sh
- chmod a+x scripts/run-build.sh
- chmod a+x scripts/remove-key.sh
- gem update --system
- gem install fastlane --no-rdoc --no-ri --no-document --quiet
install: true
before_script:
- "./scripts/add-key.sh"
- echo FASTLANE_PASSWORD=$FASTLANE_PASSWORD >> .env
script:
- xcodebuild clean build -workspace flyve-mdm-ios.xcworkspace -scheme flyve-mdm-ios
- "./scripts/run-build.sh"
after_script:
- "./scripts/remove-key.sh"
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
env:
  global:
  - APPNAME="flyve-mdm-ios"
  - PROFILE_UUID=XC_iOS_orgflyvemdmagentexample
  - KEYCHAIN_NAME="ios-app.keychain"
  - SCRIPT_PATH=./scripts
  - CERTIFICATES_PATH=./scripts/cert
  - PROFILE_PATH=./scripts/profile
  - secure: YRaBUFWOQbizFimaehLpUaQ+LglTOWcTtijBMoLmUEG4pXX6X7U1F7r+pDnjQW4rwcSzNvmjUlKvNKVC8igjts1eFq8i1757AC8/pWnLH4NAltnJmoWQ3WklBl23iVLZ+h12JTTxr7c2BKjnk+XTnKwQrdH2nUeug9PoONoH8K1e7th5mJE2FxAxcC2hP0aPopKT6pL18QNWApaBhmZJl5GxGlNnJYrE/gR7iC55L0gJYsetZMqC2VChfQLaFIwYYaG/AqptJiFoboKzL+GSGDbxe8QRcpOOzYAzfUPyhSE+HZOgan9+JLjRnUv7D0RvUceR0n0QoS4yLpajrr3zxsFRvRppexZYkNPGRVmCHeij2+z1ZfnedLuiDYugJdjvFMBnmgCCPVjCFW8MzLSH+N/yZtz6y7kzqqIeyitEpy90DQinderOQsXa3pA8UlVNtGkhLx2Tp95nhkI3TA0YQT/C9TP0fUakni7sPn1gWiFpAuwMvu5u/+/BcWumtn3lOiTo/eUEr9yIvodbpK3Ak4kjMdxs4acrkv64+umxSvwnawdZ0q1cbjpWc8PbBAEPO+YebybDryR/TAZYa0NsZiQx1AkEBe4+XctBSlUsF3hvkPoy7FH6e7rxzzpMCLnA9/U9MUJWQ0bEsjpS0kJ6AsUKVBEKLeBK49P9PUoCKlI=
