language: objective-c
osx_image: xcode8.3
xcode_workspace: flyve-mdm-ios.xcworkspace
xcode_scheme: flyve-mdm-ios
podfile: Podfile
before_install:
- chmod a+x scripts/add-key.sh
- chmod a+x scripts/run-build.sh
- chmod a+x scripts/changelog.sh
- chmod a+x scripts/remove-key.sh
- gem update --system
- gem install fastlane --no-rdoc --no-ri --no-document --quiet
- npm i -g standard-version
- brew install jq
- npm install
install: true
before_script:
- "./scripts/add-key.sh"
- echo FASTLANE_PASSWORD=$FASTLANE_PASSWORD >> .env
- echo TELEGRAM_WEBHOOKS=$TELEGRAM_WEBHOOKS >> .env
- echo GIT_REPO=$TRAVIS_REPO_SLUG >> .env
- echo GIT_BRANCH=$TRAVIS_BRANCH >> .env
script:
- "./scripts/run-build.sh"
after_script:
# - "./scripts/changelog.sh"
- "./scripts/remove-key.sh"
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
env:
  global:
  - APPNAME="flyve-mdm-ios"
  - PROFILE_UUID=XC_iOS_orgflyvemdmagent
  - KEYCHAIN_NAME="ios-app.keychain"
  - SCRIPT_PATH=./scripts
  - CERTIFICATES_PATH=./scripts/cert
  - PROFILE_PATH=./scripts/profile
  - GH_USER=flyve-mdm-bot
  - secure: YRaBUFWOQbizFimaehLpUaQ+LglTOWcTtijBMoLmUEG4pXX6X7U1F7r+pDnjQW4rwcSzNvmjUlKvNKVC8igjts1eFq8i1757AC8/pWnLH4NAltnJmoWQ3WklBl23iVLZ+h12JTTxr7c2BKjnk+XTnKwQrdH2nUeug9PoONoH8K1e7th5mJE2FxAxcC2hP0aPopKT6pL18QNWApaBhmZJl5GxGlNnJYrE/gR7iC55L0gJYsetZMqC2VChfQLaFIwYYaG/AqptJiFoboKzL+GSGDbxe8QRcpOOzYAzfUPyhSE+HZOgan9+JLjRnUv7D0RvUceR0n0QoS4yLpajrr3zxsFRvRppexZYkNPGRVmCHeij2+z1ZfnedLuiDYugJdjvFMBnmgCCPVjCFW8MzLSH+N/yZtz6y7kzqqIeyitEpy90DQinderOQsXa3pA8UlVNtGkhLx2Tp95nhkI3TA0YQT/C9TP0fUakni7sPn1gWiFpAuwMvu5u/+/BcWumtn3lOiTo/eUEr9yIvodbpK3Ak4kjMdxs4acrkv64+umxSvwnawdZ0q1cbjpWc8PbBAEPO+YebybDryR/TAZYa0NsZiQx1AkEBe4+XctBSlUsF3hvkPoy7FH6e7rxzzpMCLnA9/U9MUJWQ0bEsjpS0kJ6AsUKVBEKLeBK49P9PUoCKlI=
  - secure: lf7O3dIllZX/axUPJapc6PEKfnPX8wUNlTJFKj7cnej5EU0CAOMOa7jpX+rqD7eb+X+jDZEm4zGYler00TjhPD3HYty3809p0TIgLTS2xI9y3VQXDudWv8KoW0u++3WNmKH7Ob2jpUy4Gh5kkLG7ZDjkdsSLAZzhOthjmNAKQ+OqQrd04wuRHfTgcQ2MKHykEgxNDaFDXY/cI2m8g32oEoh7bp/FRKSFNIki1Bti6LlNKGV6a5Xw9l2pIpqnEhZlTyZOCp3mwPw1JJf8iSGrdH8TJKuCddPBKKkt4cN7L2C++QejBHWdk6sisOLVzQBgXrPspcf4W5AcqGT0uJm0pFJjg/XwTZzSujne6nXG+EFh9J/0Lv4KDjBp3/QyWIa/IUEWcCahaov7BoiO7sFIjSobDfpcugO5qM9GtgVXhUdUZyTjkVAx7e6lbStSszujRu8r7bsEJWpRhu2Qqgwazas8yi9hoeX+U1pGK+IOY2EOWZq91lH35mWDzzkI+1lnisPTW4aXQWyVkHGdvwu48xYyKGI8uWYiupvX+M+npNQ1+q5IlqnhukSlB9sGtq/ChkuOXMUA2nfx3X0li5psV8eBFNcpn7I719ivrYooddoy2qFay2fuXqB4S12bgp0A6BPwygDeVMJSegYbJSsfSq8ITH8ypzd3L404zJJsge4=
  - secure: SX3DaWWjvQYRUR3K33qZUL0bSO7itlujNqeEfW408Ufp7aAjJQJLevRuAsDYz35MJ2aH58w/oXwQjR2OBl9yqPol+BeuKAZ92Ld6psDRDiVIGcrKWJ4ouc8jdbt7ucFlJY2C8rG7Epa5t0O0r/Nxt62uruOa9cFuNyBBXrE5QQDuAhFq1HFyFjFY9Ln1IWD2YEGwWC12e9N9LNnjSMQ50WcMfrypmoTq3eVBagc1+/afKUd7gJvwJWJ8FkROsw5VoOKUpu5c+3UlbMa2cKyeDtXmHswbOU069Bci6CJFPxVlqYte2+5VdZGRwsY/vKmK/baDIlZ9dmDZxN6doJavUcN87G4kIk3VMlIpDn4QmZVJI3eViloLy8Lvw3kKnpgXkNd6+t0OmZiGzW1YZ6CBHMiYtCaAcHIOwSJUSXgHfbByxlCgg6FArCs3+2jfFH5hGfM/d8ybFeT+ad/2LAfhM878VeZJsQQ9ufDD/sHYqgrqZ45jdJEkCSooksqlPnXXxShvuHCIRU5l/yRGAQOGD0b53lh6aUshvDVHNsV6dp2i44s48dEyVjhL/vYZuqT9/gLvub2BjLU0gAhnkbUTY4qAnwimzEcUoTeM/LPwvQR2wHTsz0HmY//bUcii4m8pOiA9W0wZqSZbcvjnnxkJ+Mc00VdWToQuTWcteY72qhc=
  - secure: Rm2a42Ol5lFBXMeSRZPJrjOQw6i2GvHD5mkJVujOAqXTcuVbkZ8KFbJE1FFmw6DXHr+Tg1anyGoxQIIgn3+WXT3hqadrAEuXin2LfjCTTEWVvMrlE9fHAq08nvWhuNF/2D3kBhYw7g8eziQ4uWrlgv93grI4gwWvdp6/4ysdt8vBJ6jmrWHzZXQfsAu24Lqo3ogRvsrR6TUu67iJHBgRCbIg6sC9+keNmdBze/vDvbTrUyvzo5fpnGgX4s02S0MDUX9QiQHQ2bf+JZ3o0ogky1aXLvnUH9tNEtZOO9R/sDRYdamwNSBsMPpdnk1C1fOVZfdBuG40BfcWPL31WIR82GclGmcYOCVEEsKhVqFeSF8ffNPmr2NxTEO1k/B64nbc2umFyLsq++4fnZ4adpACEbDgY+kFCoJYD/pCjoFtfE79qBidO8RZpGcB0hsTYcIoRmTynRDrUFbgDNW79URb3T53eX4JVY02u49FQ3xTJm5e6A4MxNML7cUHj329NBoivrK/YbghYxK7MaCwtdpbjdfldrtr1LCt0cJ4aNVPyB7uh/W29CVhOggcScGFNoQ1Rj4ytspTZQoGR2JePMcPwr5sRwr13jOsHA9f+KcDdKPKOi45TuXrPQhDgJZwseGlasbFbcoiGEwshihkkK46HQWk8WS3Mjap8uEbfS0EztI=
  - secure: lo1n+t09CUFoKMTeKqirt3g6UQoMv5hz/KEv1bw4lg8LU5Qf+x6xs5pZCbTv4Hl/z7aQusBR97S6C6/dEAvmlUD480ndNxWctQfWw+3er1vAkjPe+HOt2fKhEuHmxROmyw9PEuVPCwvprm3xbVQijV6G45o/G5Ky4oVKOKL4cEZlrQqz1QrORdg3XquLCbxJyqrhisBZdHS2JnQO1z+SGfg5V2M/wYcrcPVRFf9iIq/uxjcjmfjjR1SPhe6gkzX7Huok5tkTkMwUpl5q9ADzlXXkOdSLJSQwY+Jo71Yic9YNzm8xyZ4WBcy12GQztBmM5v9IkbaPsarcfWwxyK6tGlH4Zum6ogck82gOgK652PdHmiRS24Yp/E0CRDrR3iMSUVGFnXCmrQc/LcniFLAy8drvIBD/jX+YqL19aD21blhsxUkVvvLYSwXkIfe6i7x8kXJMbvRhqDiQypVT8BpXmwzX6u5YT2r4vC+byfIN2M24gepGcKz+rhsSR/qbOf3OnnzZxnHjkThuXnV//1S9wsQBYaeP4YF8gvuUL9WMQ+XAwAuA+CPCWxRBBUif0qFn5Ix3JNELZ3ZwyZ5/6e27GwRFn1dykkQ+eSaAS86+sooZ1O4wA1DlLtOwowoTwHeKGoHs6FHZAiLyngFfxpaTXGc3Ivto4J19uMEPv4doBco=
