language: objective-c
osx_image: xcode8.3
xcode_workspace: flyve-mdm-ios.xcworkspace
xcode_scheme: flyve-mdm-ios
xcode_sdk: iphonesimulator10.3
script:
- xcodebuild clean build -workspace flyve-mdm-ios.xcworkspace -scheme flyve-mdm-ios build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
